name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    # steps:
    #   - uses: actions/checkout@v4
    #   - uses: actions/setup-go@v5

    #   - name: Checkout code
    #     uses: actions/checkout@v4

    #   - name: Setup Golang
    #     uses: actions/setup-go@v5

    steps:
      - uses: actions/setup-go@v5

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.14'
          check-latest: true
      - run: go -v

      - name: Installing Dependencies
        uses: go mod tidy

      - name: Format a Code
        run: gofmt -w .