name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v5

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true
      - name: Installing Dependencies
        run: go mod tidy

      - name: Format a Code
        run: gofmt -w .
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgpgme-dev \
            libbtrfs-dev \
            libdevmapper-dev \
            pkg-config \
            libglib2.0-dev \
            libseccomp-dev \
            gcc
      - name: Build a code
        run: go build -o congo main.go